### ISSUE TITLE
Encountered error

### ISSUE THREAD

**Issue by iskandr** [Hjertesvikt/Peptide-web-site#4]
I tried submitting the common IDH1 variant "R132H" for HLA-A02:01 and got this error:

```
Notice: Undefined variable: comma in /srv/disk1/2574633/www/padiracinnovation.org/peptide/input_errs.php on line 58

----------------------------------------------------------------------------------------------------------
We interrogated NetMHCpan with the gene "IDH1", the mutation "R132H" and the HLA allele(s) "HLA-A2:01".
* We found a point mutation case.
* Sequence submitted in FASTA format to NetMHCpan: VSGWVKPIIIGHHAYGDQYRATDF

* Origin of FASTA's sequence: http://www.uniprot.org/uniprot/O75874.fasta.

The following peptides were found by NetMHCpan:
No peptides found
```

**Comment by Hjertesvikt** [comment]
Hi and thanks for checking the code!

There was an error when checking the coherency of the lists of parameters in the form.
The check assumed that there was always several HLA alleles, and that they were separated by a comma.
But if there was only one HLA allele the code pathway never declared the variable containing the numbers of commas.
Please let me know of any other issues.
